2023-10-18 13:59:48,179 INFO    StreamThr :19764 [internal.py:wandb_internal():86] W&B internal server running at pid: 19764, started at: 2023-10-18 13:59:48.179164
2023-10-18 13:59:48,180 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status
2023-10-18 13:59:48,196 INFO    WriterThread:19764 [datastore.py:open_for_write():85] open: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\run-u1szdmjt.wandb
2023-10-18 13:59:48,196 DEBUG   SenderThread:19764 [sender.py:send():369] send: header
2023-10-18 13:59:48,230 DEBUG   SenderThread:19764 [sender.py:send():369] send: run
2023-10-18 13:59:48,629 INFO    SenderThread:19764 [dir_watcher.py:__init__():211] watching files in: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files
2023-10-18 13:59:48,629 INFO    SenderThread:19764 [sender.py:_start_run_threads():1100] run started: u1szdmjt with start time 1697633988.181164
2023-10-18 13:59:48,630 DEBUG   SenderThread:19764 [sender.py:send_request():396] send_request: summary_record
2023-10-18 13:59:48,631 INFO    SenderThread:19764 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-10-18 13:59:48,634 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: check_version
2023-10-18 13:59:48,635 DEBUG   SenderThread:19764 [sender.py:send_request():396] send_request: check_version
2023-10-18 13:59:48,672 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: run_start
2023-10-18 13:59:48,685 DEBUG   HandlerThread:19764 [system_info.py:__init__():31] System info init
2023-10-18 13:59:48,685 DEBUG   HandlerThread:19764 [system_info.py:__init__():46] System info init done
2023-10-18 13:59:48,685 INFO    HandlerThread:19764 [system_monitor.py:start():181] Starting system monitor
2023-10-18 13:59:48,685 INFO    SystemMonitor:19764 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-10-18 13:59:48,685 INFO    HandlerThread:19764 [system_monitor.py:probe():201] Collecting system info
2023-10-18 13:59:48,688 INFO    SystemMonitor:19764 [interfaces.py:start():190] Started cpu monitoring
2023-10-18 13:59:48,688 INFO    SystemMonitor:19764 [interfaces.py:start():190] Started disk monitoring
2023-10-18 13:59:48,689 INFO    SystemMonitor:19764 [interfaces.py:start():190] Started gpu monitoring
2023-10-18 13:59:48,692 INFO    SystemMonitor:19764 [interfaces.py:start():190] Started memory monitoring
2023-10-18 13:59:48,696 INFO    SystemMonitor:19764 [interfaces.py:start():190] Started network monitoring
2023-10-18 13:59:48,702 DEBUG   HandlerThread:19764 [system_info.py:probe():195] Probing system
2023-10-18 13:59:48,703 DEBUG   HandlerThread:19764 [system_info.py:_probe_git():180] Probing git
2023-10-18 13:59:48,704 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:48,704 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_info.py:_probe_git():188] Probing git done
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_info.py:probe():240] Probing system done
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.9.15', 'heartbeatAt': '2023-10-18T12:59:48.702882', 'startedAt': '2023-10-18T12:59:48.165165', 'docker': None, 'cuda': None, 'args': ('--algo', 'gpi_ls_discrete', '--env-id', 'deep-sea-treasure-v0', '--num-timesteps', '40000', '--gamma', '0.99', '--ref-point', '4000'), 'state': 'running', 'program': 'C:\\Users\\19233436\\PycharmProjects\\MOGE\\launch_experiment.py', 'codePath': 'launch_experiment.py', 'git': {'remote': 'https://github.com/JLu2022/MOGE.git', 'commit': 'caae01c0382da946b2eb1ca6e765981dbf8c2193'}, 'email': 'junlinlu16@gmail.com', 'root': 'C:/Users/19233436/PycharmProjects/MOGE', 'host': 'DESKTOP-UUPRB15', 'username': '19233436', 'executable': 'C:\\Users\\19233436\\Anaconda3\\envs\\MAPI\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2400.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 2400.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'total': 951.1328086853027, 'used': 196.7255859375}, 'gpu': 'NVIDIA T1000', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA T1000', 'memory_total': 4294967296}], 'memory': {'total': 31.696025848388672}}
2023-10-18 13:59:48,753 INFO    HandlerThread:19764 [system_monitor.py:probe():211] Finished collecting system info
2023-10-18 13:59:48,753 INFO    HandlerThread:19764 [system_monitor.py:probe():214] Publishing system info
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_info.py:_save_pip():67] Saving pip packages done
2023-10-18 13:59:48,753 DEBUG   HandlerThread:19764 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-10-18 13:59:48,755 ERROR   HandlerThread:19764 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\19233436\Anaconda3\envs\MAPI\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\19233436\Anaconda3\envs\MAPI\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\19233436\Anaconda3\envs\MAPI\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\19233436\Anaconda3\envs\MAPI\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-10-18 13:59:48,756 DEBUG   HandlerThread:19764 [system_info.py:_save_conda():86] Saving conda packages done
2023-10-18 13:59:48,756 DEBUG   HandlerThread:19764 [system_info.py:_save_code():89] Saving code
2023-10-18 13:59:48,778 DEBUG   HandlerThread:19764 [system_info.py:_save_code():110] Saving code done
2023-10-18 13:59:48,778 DEBUG   HandlerThread:19764 [system_info.py:_save_patches():127] Saving git patches
2023-10-18 13:59:48,892 DEBUG   HandlerThread:19764 [system_info.py:_save_patches():169] Saving git patches done
2023-10-18 13:59:48,893 INFO    HandlerThread:19764 [system_monitor.py:probe():216] Finished publishing system info
2023-10-18 13:59:48,913 DEBUG   SenderThread:19764 [sender.py:send():369] send: files
2023-10-18 13:59:48,913 INFO    SenderThread:19764 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-10-18 13:59:48,913 INFO    SenderThread:19764 [sender.py:_save_file():1354] saving file code\launch_experiment.py with policy now
2023-10-18 13:59:48,913 INFO    SenderThread:19764 [sender.py:_save_file():1354] saving file diff.patch with policy now
2023-10-18 13:59:48,917 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: stop_status
2023-10-18 13:59:48,917 DEBUG   SenderThread:19764 [sender.py:send_request():396] send_request: stop_status
2023-10-18 13:59:49,087 DEBUG   SenderThread:19764 [sender.py:send():369] send: telemetry
2023-10-18 13:59:49,087 DEBUG   SenderThread:19764 [sender.py:send():369] send: metric
2023-10-18 13:59:49,087 WARNING SenderThread:19764 [sender.py:send_metric():1305] Seen metric with glob (shouldn't happen)
2023-10-18 13:59:49,087 DEBUG   SenderThread:19764 [sender.py:send():369] send: telemetry
2023-10-18 13:59:49,088 DEBUG   SenderThread:19764 [sender.py:send():369] send: telemetry
2023-10-18 13:59:49,088 DEBUG   SenderThread:19764 [sender.py:send():369] send: config
2023-10-18 13:59:49,088 DEBUG   SenderThread:19764 [sender.py:send():369] send: config
2023-10-18 13:59:49,120 INFO    wandb-upload_1:19764 [upload_job.py:push():113] Skipped uploading C:\Users\19233436\AppData\Local\Temp\tmpzar0qjotwandb\hjseqaao-code/launch_experiment.py
2023-10-18 13:59:49,348 INFO    wandb-upload_0:19764 [upload_job.py:push():133] Uploaded file C:\Users\19233436\AppData\Local\Temp\tmpzar0qjotwandb\r5yg5r77-wandb-metadata.json
2023-10-18 13:59:49,479 INFO    wandb-upload_2:19764 [upload_job.py:push():133] Uploaded file C:\Users\19233436\AppData\Local\Temp\tmpzar0qjotwandb\wqlhxqpc-diff.patch
2023-10-18 13:59:49,638 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\output.log
2023-10-18 13:59:49,638 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\wandb-summary.json
2023-10-18 13:59:49,638 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\code\launch_experiment.py
2023-10-18 13:59:49,638 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\diff.patch
2023-10-18 13:59:49,638 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\conda-environment.yaml
2023-10-18 13:59:49,639 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\requirements.txt
2023-10-18 13:59:49,639 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\wandb-metadata.json
2023-10-18 13:59:49,639 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\code
2023-10-18 13:59:50,719 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:50,719 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:51,655 INFO    Thread-16 :19764 [dir_watcher.py:_on_file_modified():289] file/dir modified: C:\Users\19233436\PycharmProjects\MOGE\wandb\run-20231018_135948-u1szdmjt\files\output.log
2023-10-18 13:59:52,737 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:52,737 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:53,533 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status_report
2023-10-18 13:59:54,751 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:54,751 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:56,770 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:56,770 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:58,568 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status_report
2023-10-18 13:59:58,782 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 13:59:58,782 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:00,803 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:00,803 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:02,819 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:02,819 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:03,623 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status_report
2023-10-18 14:00:03,925 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: stop_status
2023-10-18 14:00:03,925 DEBUG   SenderThread:19764 [sender.py:send_request():396] send_request: stop_status
2023-10-18 14:00:04,826 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:04,826 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:06,839 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:06,839 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:08,856 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:08,856 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:09,213 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status_report
2023-10-18 14:00:10,865 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:10,865 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:12,877 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:12,877 ERROR   gpu       :19764 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-18 14:00:14,257 DEBUG   HandlerThread:19764 [handler.py:handle_request():144] handle_request: status_report
2023-10-18 14:00:14,800 INFO    cpu       :19764 [interfaces.py:monitor():140] Process cpu has exited.
2023-10-18 14:00:14,801 DEBUG   SystemMonitor:19764 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-10-18 14:00:14,801 DEBUG   SystemMonitor:19764 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-10-18 14:00:14,801 DEBUG   SystemMonitor:19764 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-10-18 14:00:14,842 ERROR   gpu       :19764 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-10-18 14:00:14,844 DEBUG   SenderThread:19764 [sender.py:send():369] send: stats
2023-10-18 14:00:15,943 INFO    MainThread:19764 [internal.py:handle_exit():76] Internal process exited
